apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "app-1.labels" . | nindent 4 }}
  name: deploy-{{ $.Release.Name }}
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      {{- include "app-1.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-1.labels" . | nindent 8 }}
    spec:
      serviceAccountName: sa-{{ $.Release.Name }}
      containers:
      - image: {{ $.Values.image.name }}:{{ $.Values.image.tag }}
        name: nginx
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        resources:
          requests:
            memory: {{ $.Values.resources.requests.memory }}
            cpu: {{ $.Values.resources.requests.cpu }}
          limits:
            memory: {{ $.Values.resources.limits.memory }}
            cpu: {{ $.Values.resources.limits.cpu }}